import '@fortawesome/fontawesome-free/css/all.css';
import Vue from 'vue';
import Vuetify, {
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VAvatar,
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VChip,
  VCol,
  VContainer,
  VContent,
  VDataTable,
  VDialog,
  VDivider,
  VFileInput,
  VForm,
  VIcon,
  VMain,
  VNavigationDrawer,
  VRow,
  VSelect,
  VSkeletonLoader,
  VSpacer,
  VTab,
  VTabItem,
  VTabs,
  VTabsSlider,
  VTextField,
  VToolbar,
  VToolbarTitle,
  VTooltip,
} from 'vuetify/lib';

Vue.use(Vuetify, {
  components: {
    VApp,
    VAppBar,
    VAppBarNavIcon,
    VAvatar,
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VChip,
    VCol,
    VContainer,
    VContent,
    VDataTable,
    VDialog,
    VDivider,
    VFileInput,
    VForm,
    VIcon,
    VMain,
    VNavigationDrawer,
    VRow,
    VSelect,
    VSkeletonLoader,
    VSpacer,
    VTab,
    VTabItem,
    VTabs,
    VTabsSlider,
    VTextField,
    VToolbar,
    VToolbarTitle,
    VTooltip,
  },
  directives: {},
});

export default new Vuetify({
  icons: {
    iconfont: 'fa',
  },
  lang: {
    current: 'en',
  },
  theme: {
    default: 'light',
    themes: {
      light: {
        primary: '#38A0FA',
        secondary: '#25E2AA',
        accent: '#8c9eff',
        error: '#b71c1c',
        base: '#0C2366',
        mainDarkBlue: '#0C2366',
        mainLightGrey: '#F5F5F5',
      },
    },
  },
});
